	var youre = Array(
		"You're the Cardi B<br>to my wet a** p*ssy.",
		"You're the Lindsay to my Lohan.",
		"You're the Ron to my Hermione.",
		"You're the dill to my pickle.",
		"You're the password to my wifi.",
		"You're the 'g'day' to my mate.",
		"You're the Jeff Bezos to my enormous wealth gap.",
		"You're the 'maybe later' to my software update.",
		"You're the cream to my cheese.",
		"You're the white Vans to my 'damn, Daniel!'",
		"You're the attention-seeking to my Kim Kardashian.",
		"You're the You to my Tube.",
		"You're the golden shower to my Donald Trump.",
		"You're the apocalypse to my 2020.",
		"You're the Tik to my Tok.",
		"You're the Grimes to my Elon Musk.",
		"You're the face mask to my hand sanitizer.",
		"You're the peanut butter to my baby.",
		"You're the Andy to my tuna.",
		"You're the beard to my neck.",
		"You're the fedora to my 'm'lady'.",
		"You're the 'wow' to my 'can you not?'",
		"You're the toilet paper to my quarantine.",
		"You're the snatched wig to my drag queen.",
		"You're the 'um' to my 'excuse me'.",
		"You're the Netflix to my chill.",
		"You're the white girl to my wasted.",
		"You're the reproductive rights to my uterus.",
		"You're the 'ugh' to my 'whatever'.",
		"You're the lower back pain to my early 30s.",
		"You're the 'the' to my 'my'.",
		"You're the 'skip ad' to my sponsored message.",
		"You're the FOMO to my YOLO.",
		"You're the edible to my stoner movie.",
		"You're the 'oops! I...'' to my 'did it again'.",
		"You're the chai to my latte.",
		"You're the jelly bracelet to my butterfly hairclip.",
		"You're the loonie to my toonie.",
		"You're the Buffy to my Gilmore Girls.",
		"You're the trainwreck to my Game of Thrones ending.",
		"You're the 'hey now' to my 'you're an all star'.",
		"You're the loonie to my toonie.",
		"You're the Marilyn to my Manson.",
		"You're the purple to my nurple.",
		"You're the 'ah-'' to my 'choo!'",
		"You're the 'knock, knock' to my 'who's there?'",
		"You're the baby Yoda to my Star Wars franchise.",
		"You're the cinnamon to my candy heart.",
		"You're the Cady Haron to my Aaron Samuels.",
		"You're the go to my Glen Coco.",
		"You're the corn to my cob.",
		"You're the horn to my unicorn.",
		"You're the Donkey to my Kong.",
		"You're the soy milk to my tofu burger.",
		"You're the 9-5 to my soul-crushing desk job.",
		"You're the Beavis to my Butthead.",
		"You're the Carmela to my Tony Soprano.",
		"You're the pride to my rainbow.",
		"You're the Borat to my 'very nice!'",
		"You're the Rick to my Morty.",
		"You're the Kamala to my Harris.",
		"You're the Michelle to my Barack Obama.",
		"You're the data surveillance to my tech capitalism.",
		"You're the 'keep watching' to my 'are you still there?'",
		"You're the Ben to my Jerry.",
		"You're the DIY to my charcoal face mask.",
		"You're the hyaluronic acid to my skincare addiction.",
		"You're the shellac to my manicure.",
		"You're the green eggs to my ham.",
		"You're the chocolate bunny to my Easter egg.",
		"You're the 'holy sh*t!'' to my 'Jesus Christ!'",
		"You're the 'girl' to my 'please'.",
		"You're the Xbox to my student loans.",
		"You're the meat to my potatoes.",
		"You're the emo to my screamo.",
		"You're the Tumblr to my MySpace.",
		"You're the Ouija board to my seance.",
		"You're the 'wait' to my 'what?'",
		"You're the 'nm' to my 'u?'",
		"You're the groan to my dad joke.",
		"You're the Fettucini to my Alfredo.",
		"You're the 'f*ck it' to my New Years resolution.",
		"You're the Mariah Carey to my dolphin whistle.",
		"You're the head gear to my 4 years of braces.",
		"You're the wrinkles to my acne.",
		"You're the sports car to my mid-life crisis.",
		"You're the 'howdy folks' to my 'what can I do for ya?'",
		"You're the 2:43am to my 'you up?'",
		"You're the 'om' to my 'nom nom'.",
		"You're the addictive quality to my pointless website.",
		"You're the gravy to my cranberry sauce.",
		"You're the 'ouch!' to my Charlie.",
		"You're the friday at 5 to my work week.",
		"You're the 'stop' to my 'hammer time'.",
		"You're the 'skip intro' to my 9th Office rewatch.",
		"You're the anesthetic to my root canal.",
		"You're the mustache to my Movember.",
		"You're the wingardium to my leviosa.",
		"You're the butter to my bread.",
		"You're the love to my live laugh.",
		"You're the Canada Goose jacket to my King St W.",
		"You're the convenience store to my midnight snack.",
		"You're the guac to my burrito.",
		"You're the starter to my sourdough bread.",
		"You're the 99.9% effectiveness to my vaccine.",
		"You're the lint the bellybutton.",
		"You're the cat video to my rabbit hole.",
		"You're the lube to my tube.",
		"You're the custom search to my PornHub.",
		"You're the disheveled spokesman to my Trivago.",
		"You're the leave-in treatment to my split ends.",
		"You're the Pepto to my acid reflux.",
		"You're the coffee to my morning.",
		"You're the mute button to my Zoom call.",
		"You're the cirque to my soleil.",
		"You're the Abbi to my Ilana.",
		"You're the hand sanitizer to my 2020.",
		"You're the Kawhi Leonard to my rare and fleeting emotions.",
		"You're the 'ignore' to my new friend request",
		"You're the snooze button to my alarm clock."
		);

function randomYoure() {
  var randomYoure = youre[Math.floor(Math.random() * youre.length)];
  document.getElementById('randomYoure').value = randomYoure;
}


function copy() {
  let randomYoure = document.getElementById("randomYoure");
  randomYoure.select();
  document.execCommand("copy");
}