	var youre = Array(
		"You're the\nCardi B\nto my\nwet a** p*ssy.",
		"You're the\nHarry\nto my\nSally.",
		"You're the\nRon\nto my\nHermione.",
		"You're the\ndill\nto my\npickle.",
		"You're the\npassword\nto my\nWiFi.",
		"You're the\n'g'day'\nto my\nmate.",
		"You're the\nJeff Bezos\nto my\nenormous wealth gap.",
		"You're the\n'maybe later'\nto my\nsoftware update.",
		"You're the\ncream\nto my\ncheese.",
		"You're the\nwhite Vans\nto my\n'damn, Daniel!'",
		"You're the\nKanye\nto my\nKim Kardashian.",
		"You're the\nYou\nto my\nTube.",
		"You're the\ngolden shower\nto my\nDonald Trump.",
		"You're the\nMarissa\nto my\nO.C. watch party.",
		"You're the\nTik\nto my\ntok.",
		"You're the\nGrimes\nto my\nElon Musk.",
		"You're the\nhand sanitizer\nto my\n2020 pandemic.",
		"You're the\npeanut\nto my\nbutter.",
		"You're the\nAndy\nto my\ntuna.",
		"You're the\nrazor\nto my\nneckbeard.",
		"You're the\nfedora\nto my\n'm'lady'.",
		"You're the\n'wow'\nto my\n'can you not?'",
		"You're the\ntoilet paper\nto my\nquarantine.",
		"You're the\nsnatched wig\nto my\ndrag queen dreams.",
		"You're the\npassive aggressive email\nto my\nwork conflict.",
		"You're the\nNetflix\nto my\nchill.",
		"You're the\nwhite girl\nto my\nwasted.",
		"You're the\nreproductive rights\nto my\nuterus.",
		"You're the\nmute button\nto my\nzoom call.",
		"You're the\nRobaxx\nto my\nlower back pain.",
		"You're the\n'skip ad'\nto my\nsponsored message.",
		"You're the\nYOLO\nto my\nFOMO.",
		"You're the\nedible\nto my\nstoner movie.",
		"You're the\n'oops! I...''\nto my\n'did it again'.",
		"You're the\nchai\nto my\nlatte.",
		"You're the\njelly bracelet\nto my\nhigh school dance.",
		"You're the\nseasons 1 through 7\nto my\nGame of Thrones.",
		"You're the\n'hey now'\nto my\n'all star'.",
		"You're the\npurple\nto my\nnurple.",
		"You're the\n'ah-''\nto my\n'choo!'",
		"You're the\n'knock, knock'\nto my\n'who's there?'",
		"You're the\nbaby Yoda\nto my\nStar Wars franchise.",
		"You're the\ncinnamon\nto my\ncandy heart.",
		"You're the\nCady Haren\nto my\nAaron Samuels.",
		"You're the\n'you go'\nto my\nGlen Coco.",
		"You're the\ncorn\nto my\ncob.",
		"You're the\nhorn\nto my\nunicorn.",
		"You're the\nDonkey\nto my\nKong.",
		"You're the\ncheese\nto my\nburger.",
		"You're the\n5PM\nto my\nsoul-crushing desk job.",
		"You're the\nBeavis\nto my\nButthead.",
		"You're the\nCarmela\nto my\ntony Soprano.",
		"You're the\npride\nto my\nrainbow.",
		"You're the\nRick\nto my\nMorty.",
		"You're the\nKamala\nto my\nBiden.",
		"You're the\nMichelle\nto my\nBarack Obama.",
		"You're the\ndata surveillance\nto my\ntech capitalism.",
		"You're the\n'keep watching'\nto my\n'are you still there?'",
		"You're the\nBen\nto my\nJerry.",
		"You're the\nactivated charcoal\nto my\ncleansing face mask.",
		"You're the\nhyaluronic acid\nto my\nskincare addiction.",
		"You're the\nshellac\nto my\nmanicure.",
		"You're the\ngreen eggs\nto my\nham.",
		"You're the\nchocolate bunny\nto my\nEaster hunt.",
		"You're the\n'girl'\nto my\n'please'.",
		"You're the\nCOD\nto my\nXBOX.",
		"You're the\nmeat\nto my\npotatoes.",
		"You're the\nemo\nto my\nscreamo.",
		"You're the\ncontroversial comment\nto my\nTumblr.",
		"You're the\nOuija board\nto my\nseance.",
		"You're the\ncheesy punchline\nto my\ndad joke.",
		"You're the\nFettucini\nto my\nAlfredo.",
		"You're the\n'f*ck it'\nto my\nNew Years resolution.",
		"You're the\nMariah Carey\nto my\ndolphin whistle.",
		"You're the\nsports car\nto my\nmid-life crisis.",
		"You're the\n'howdy folks'\nto my\n'what can I do for ya?'",
		"You're the\n'u up?' text\nto my\n2:43am.'",
		"You're the\n'om'\nto my\n'nom nom'.",
		"You're the\naddictive quality\nto my\npointless website.",
		"You're the\ngravy\nto my\nturkey dinner.",
		"You're the\n'stop'\nto my\n'hammer time'.",
		"You're the\n'skip intro'\nto my\n9th Office rewatch.",
		"You're the\nanesthetic\nto my\nroot canal.",
		"You're the\nmustache\nto my\nMovember.",
		"You're the\nwingardium\nto my\nleviosa.",
		"You're the\nbutter\nto my\nbread.",
		"You're the\n'love'\nto my\n'live laugh'.",
		"You're the\nCanada Goose jacket\nto my\nKing St West.",
		"You're the\nconvenience store\nto my\nmidnight snack.",
		"You're the\nguac\nto my\nburrito.",
		"You're the\nyeast starter\nto my\nsourdough bread.",
		"You're the\n99.9% effectiveness\nto my\nvaccine.",
		"You're the\nlint\nto my\nbelly button.",
		"You're the\ncat video\nto my\nrabbit hole.",
		"You're the\ncustom search\nto my\nporn experience.",
		"You're the\ndisheveled spokesman\nto my\nTrivago.",
		"You're the\nOlaplex\nto my\nsplit ends.",
		"You're the\nPepto\nto my\nacid reflux.",
		"You're the\ncoffee\nto my\nmorning.",
		"You're the\ncirque\nto my\nsoleil.",
		"You're the\nAbbi\nto my\nIlana.",
		"You're the\n'ignore'\nto my\nnew friend requests.",
		"You're the\nsnooze\nto my\nalarm clock.",
		"You're the\npeach\nto my\nfruit basket.",
		"You're the\nfly\nto my\nMike Pence head.",
		"You're the\ndoody\nto my\nhowdy.",
		"You're the\nnude portrait\nto my\niconic boat cruise.",
		"You're the\nsexy pottery scene\nto my\niconic romance film.",
		"You're the\nM&Ms\nto my\nmovie theatre popcorn.",
		"You're the\nlegitimate result\nto my\n2020 election.",
		"You're the\n'1-800'\nto my\n'did-I-ask?'.",
		"You're the\nvulnerability\nto my\nhealthy relationship.",
		"You're the\nYin\nto my\nYang.",
		"You're the\ninfinity stone\nto my\ninfinity gauntlet.",
		"You're the\ntony Stark\nto my\nPeter Parker.",
		"You're the\nMiles Morales\nto my\nSpiderverse.",
		"You're the\nroo\nto my\ndoo-doo-doo-doo.",
		"You're the\ndoodle\nto my\nboring conference call.",
		"You're the\nDwight Shrute\nto my\nDunder Mifflin.",
		"You're the\nCreed Bratton\nto my\nconference meeting.",
		"You're the\nace\nto my\ndeck of cards.",
		"You're the\nwater\nto my\npoorly maintained house plant.",
		"You're the\nboop\nto my\nsnoot.",
		"You're the\nmmm\nto my\nbop.",
		"You're the\nBoardwalk\nto my\nMonopoly.",
		"You're the\nred butt\nto my\nrecess.",
		"You're the\nmonochromatic outfit\nto my\ncult.",
		"You're the\nnightmares\nto my\nmurder podcast obsession.",
		"You're the\nScooby\nto my\nDoo.",
		"You're the\ntop\nto my\nmuffin.",
		"You're the\nsophisticated burn\nto my\nsassy Alex Trebek.",
		"You're the\nright\nto my\nTinder swipe.",
		"You're the\nsideburns\nto my\nJohn Travolta.",
		"You're the\nmain character kill-off\nto my\nGame of Thrones.",
		"You're the\nchocolate\nto my\nperiod week.",
		"You're the\nlaugh track\nto my\nBig Bang Theory.",
		"You're the\nbread recipe\nto my\nquarantine.",
		"You're the\nvaccine\nto my\nCOVID-19.",
		"You're the\nacceptance\nto my\nradical self.",
		"You're the\nbees\nto my\nknees.",
		"You're the\npajamas\nto my\ncat.",
		"You're the\nsubtitles\nto my\naction movie.",
		"You're the\njoke\nto my\nawkward moment.",
		"You're the\ncheddar biscuits\nto my\nRed Lobster.",
		"You're the\ndouble tap\nto my\nIG post.",
		"You're the\ndouble knot\nto my\nrunning shoes.",
		"You're the\nfree bread\nto my\noverpriced dinner.",
		"You're the\nXL chocolate bar\nto my\Halloween.",
		"You're the\nUsher\nto my\nearly 2000's club night.",
		"You're the\nluxury candle\nto my\nliving room.",
		"You're the\nfree\ntoothbrush\nto my\ndentist appointment.",
		"You're the\n'all done'\nto my\npap smear.",
		"You're the\nwood oven\nto my\nMontreal style bagel.",
		"You're the\nAngela\nto my\nDwight.",
		"You're the\nJim\nto my\nPam.",
		"You're the\njam\nto my\npeanut butter.",
		"You're the\nrecovery day\nto my\nworkout week.",
		"You're the\ncancelled meeting\nto my\nFriday.",
		"You're the\npumpkin spice\nto my\nlatte.",
		"You're the\nrat chef\nto my\nPixar film.",
		"You're the\nmimosa\nto my\nbrunch.",
		"You're the\nbloody caesar\nto my\nhangover.",
		"You're the\ndill\nto my\npotato salad.",
		"You're the\nstimulus cheque\nto my\nglobal pandemic.",
		"You're the\nbest friend\nto my\nwedding.",
		"You're the\nflute\nto my\nLizzo lips.",
		"You're the\nbutterfly clips\nto my\nsnatched 90's hairstlye.",
		"You're the\ngum\nto my\nblow pop.",
		"You're the\nplatinum card\nto my\nPokemon pack.",
		"You're the\nrecord low interest rate\nto my\nmortgage.",
		"You're the\nprotein shake\nto my\npost-workout.",
		"You're the\nmacros\nto my\ngains.",
		"You're the\njailtime\nto my\nHarvey Weinstein scandal.",
		"You're the\nAOC\nto my\nUS congress.",
		"You're the\nwind\nto my\nwings.",
		"You're the\n'lol'\nto my\nawkward text convo.",
		"You're the\nNimbus 2000\nto my\nquidditch game.",
		"You're the\nSirius\nto my\nHarry Potter series.",
		"You're the\ntime warp effect\nto my\nTikTok.",
		"You're the\nnotificaiton\nto my\nsocial media addiction.",
		"You're the\nWWOOMMMMMMM\nto my\nChris Nolan film.",
		"You're the\nfather\nto my\nDarth Vader.",
		"You're the\nSamwise\nto my\nFrodo.",
		"You're the\nmutual consent\nto my\nsexual encounter.",
		"You're the\nshell\nto my\nturtle bod.",
		"You're the\ntutti frutti\nto my\nJelly Bellies.",
		"You're the\ntulip field\nto my\nscenic Amsterdam adventure.",
		"You're the\nJeff Goldblum\nto my\nJurassic Park.",
		"You're the\nvote\nto my\npolitical election.",
		"You're the\nsmoked paprika\nto my\nspice rack.",
		"You're the\nfree cookie\nto my\nplane ride.",
		"You're the\nonion\nto my\neverything bagel.",
		"You're the\nVision\nto my\nWanda.",
		"You're the\ncream center\nto my\nOreo.",
		"You're the\ncookie exterior\nto my\nOreo.",
		"You're the\nTide Pod\nto my\nforbidden snack.",
		"You're the\nketchup\nto my\nmac and cheese.",
		"You're the\nbreeze\nto my\nopen road.",
		"You're the\nalternate route\nto my\ntraffic jam.",
		"You're the\nsupplement\nto my\niron deficiency.",
		"You're the\nB12 shot\nto my\nirritable tendancies.",
		/*"You're the\nhand-knit mittens\nto my\nBernie Sanders inaguration appearance.",   \ntoO LONG :( */
		"You're the\nice cream\nto my\nhot summer day.",
		"You're the\nTammy\nto my\nRon Swanson.",
		"You're the\ncheese\nto my\nKETO diet.",
		"You're the\nUber Eats\nto my\nquarantine.",
		"You're the\npopsicle\nto my\npool party.",
		"You're the\nSaturday\nto my\nMonday\nto Friday.",
		"You're the\nVix rub\nto my\ndry cough.",
		"You're the\nEiffel\ntower\nto my\neurotrip.",
		"You're the\nelder wand\nto my\ndeathly hallows.",
		"You're the\nethical diamond\nto my\nengagement ring.",
		"You're the\nImpossible burger\nto my\nvegetarian diet.",
		"You're the\nshellac\nto my\nmanicure.",
		"You're the\nmarshmallows\nto my\nhot chocolate.",
		"You're the\nsunscreen\nto my\nIrish skin.",
		"You're the\nNew Balance shoes\nto my\nwideset feet.",
		"You're the\ncoaster\nto my\ncoffee table.",
		"You're the\nPS5\nto my\nliving room.",
		"You're the\nrecovered Word doc\nto my\ncomputer crash.",
		"You're the\nnoodles\nto my\nchicken soup.",
		"You're the\nmuscle tee\nto my\n'sup bro'.",
		"You're the\nserum\nto my\nskin care routine.",
		"You're the\ntop 8\nto my\nMyspace.",
		"You're the\ncooldown\nto my\nHIIT workout.",
		"You're the\nfart\nto my\nindigestion.",
		"You're the\nflip\nto my\nflop.",
		"You're the\nneedle\nto my\ncompass.",
		"You're the\nwindow\nto my\nwall.",
		"You're the\nmilk\nto my\ncookies.",
		"You're the\nwindow seat\nto my\nplane ride.",
		"You're the\numbrella\nto my\nrainy day.",
		"You're the\nLebron James\nto my\nbasketball.",
		"You're the\nGoku\nto my\nDragonball.",
		"You're the\npleats\nto my\npants.",
		"You're the\nsquats\nto my\nleg day.",
		/*"You're the\noverwhelmingly happy memory\nto my\npatronus charm.",   \ntoO LONG :( */
		"You're the\nbutter\nto my\npopcorn.",
		"You're the\ngas\nto my\ncar.",
		"You're the\nbubble\nto my\ntea.",
		/*"You're the\nnoise cancelling headphones\nto my\nopen concept workspace.",   \ntoO LONG :( */
		"You're the\nheadphones\nto my\ngym workout.",
		"You're the\nfire\nto my\nhot air balloon.",
		"You're the\nensuite laundry\nto my\n500 square foot condo.",
		"You're the\nbaby shark\nto my\ndoo doo doo doo.",
		"You're the\npower on sound\nto my\nPS5.",
		"You're the\ndouble\nto my\nraindbow.",
		"You're the\navocado\nto my\nhealthy lifestlye.",
		"You're the\nhee hee\nto my\nMichael Jackson.",

		
			
		);

function randomYoure() {
  var randomYoure = youre[Math.floor(Math.random() * youre.length)];
  document.getElementById('randomYoure').value = randomYoure;
}


function copy() {
  let randomYoure = document.getElementById("randomYoure");
  randomYoure.select();
  document.execCommand("copy");
}