	var youre = Array(
		"You're the Cardi B<br>to my wet a** p*ssy.",
		"You're the Lindsay to my Lohan.",
		"You're the Ron to my Hermione.",
		"You're the dill to my pickle.",
		"You're the password to my wifi.",
		"You're the 'g'day' to my mate.",
		"You're the Jeff Bezos to my enormous wealth gap.",
		"You're the 'maybe later' to my software update.",
		"You're the cream to my cheese.",
		"You're the white Vans to my 'damn, Daniel!'",
		"You're the Kanye to my Kim Kardashian.",
		"You're the You to my Tube.",
		"You're the golden shower to my Donald Trump.",
		"You're the apocalypse to my 2020.",
		"You're the Tik to my Tok.",
		"You're the Grimes to my Elon Musk.",
		"You're the hand sanitizer to my 2020 pandemic.",
		"You're the peanut to my butter.",
		"You're the Andy to my tuna.",
		"You're the beard to my neck.",
		"You're the fedora to my 'm'lady'.",
		"You're the 'wow' to my 'can you not?'",
		"You're the toilet paper to my quarantine.",
		"You're the snatched wig to my drag queen dreams.",
		"You're the 'um' to my 'excuse me'.",
		"You're the Netflix to my chill.",
		"You're the white girl to my wasted.",
		"You're the reproductive rights to my uterus.",
		"You're the 'ugh' to my 'whatever'.",
		"You're the lower back pain to my early 30s.",
		"You're the 'skip ad' to my sponsored message.",
		"You're the FOMO to my YOLO.",
		"You're the edible to my stoner movie.",
		"You're the 'oops! I...'' to my 'did it again'.",
		"You're the chai to my latte.",
		"You're the jelly bracelet to my butterfly hairclip.",
		"You're the loonie to my toonie.",
		"You're the seasons 1 through 7 to my Game of Thrones.",
		"You're the 'hey now' to my 'all star'.",
		"You're the Marilyn to my Manson.",
		"You're the purple to my nurple.",
		"You're the 'ah-'' to my 'choo!'",
		"You're the 'knock, knock' to my 'who's there?'",
		"You're the baby Yoda to my Star Wars franchise.",
		"You're the cinnamon to my candy heart.",
		"You're the Cady Haren to my Aaron Samuels.",
		"You're the 'go' to my Glen Coco.",
		"You're the corn to my cob.",
		"You're the horn to my unicorn.",
		"You're the Donkey to my Kong.",
		"You're the cheese to my burger.",
		"You're the 5PM to my soul-crushing desk job.",
		"You're the Beavis to my Butthead.",
		"You're the Carmela to my Tony Soprano.",
		"You're the pride to my rainbow.",
		"You're the Borat to my 'very nice!'",
		"You're the Rick to my Morty.",
		"You're the Kamala to my Biden.",
		"You're the Michelle to my Barack Obama.",
		"You're the data surveillance to my tech capitalism.",
		"You're the 'keep watching' to my 'are you still there?'",
		"You're the Ben to my Jerry.",
		"You're the activated charcoal to my face mask.",
		"You're the hyaluronic acid to my skincare addiction.",
		"You're the shellac to my manicure.",
		"You're the green eggs to my ham.",
		"You're the chocolate bunny to my Easter hunt.",
		"You're the 'holy sh*t!'' to my 'Jesus Christ!'",
		"You're the 'girl' to my 'please'.",
		"You're the COD to my XBOX.",
		"You're the meat to my potatoes.",
		"You're the emo to my screamo.",
		"You're the offensive comment to my Tumblr.",
		"You're the Ouija board to my seance.",
		"You're the 'wait' to my 'what?'",
		"You're the 'nm' to my 'u?'",
		"You're the groan to my dad joke.",
		"You're the Fettucini to my Alfredo.",
		"You're the 'f*ck it' to my New Years resolution.",
		"You're the Mariah Carey to my dolphin whistle.",
		"You're the sports car to my mid-life crisis.",
		"You're the 'howdy folks' to my 'what can I do for ya?'",
		"You're the 2:43am to my 'you up?'",
		"You're the 'om' to my 'nom nom'.",
		"You're the addictive quality to my pointless website.",
		"You're the gravy to my turkey dinner.",
		"You're the 'ouch!' to my Charlie.",
		"You're the 'stop' to my 'hammer time'.",
		"You're the 'skip intro' to my 9th Office rewatch.",
		"You're the anesthetic to my root canal.",
		"You're the mustache to my Movember.",
		"You're the wingardium to my leviosa.",
		"You're the butter to my bread.",
		"You're the 'love' to my 'live laugh'.",
		"You're the Canada Goose jacket to my King St West.",
		"You're the convenience store to my midnight snack.",
		"You're the guac to my burrito.",
		"You're the yeast starter to my sourdough bread.",
		"You're the 99.9% effectiveness to my vaccine.",
		"You're the lint to my bellybutton.",
		"You're the cat video to my rabbit hole.",
		"You're the lube to my tube.",
		"You're the custom search to my porn watching experience.",
		"You're the disheveled spokesman to my Trivago.",
		"You're the leave-in treatment to my split ends.",
		"You're the Pepto to my acid reflux.",
		"You're the coffee to my morning.",
		"You're the mute button to my Zoom call.",
		"You're the cirque to my soleil.",
		"You're the Abbi to my Ilana.",
		"You're the Kawhi Leonard to my rare and fleeting emotions.",
		"You're the 'ignore' to my new friend requests.",
		"You're the snooze to my alarm clock.",
		"You're the peach to my fruit basket.",
		"You're the fly to my Mike Pence head.",
		"You're the doodie to my howdie.",
		"You're the nude portrait to my boat cruise.",
		"You're the sexy pottery scene to my iconic romance film.",
		"You're the baby in my corner.",
		"You're the M&Ms to my movie theatre popcorn.",
		"You're the legitimate result to my 2020 election.",
		"You're the '1-800' to my 'did-I-ask?'.",
		"You're the vulnerability to my strong and healthy relationship.",
		"You're the Yin to my Yang.",
		"You're the infinity stone to my finger snap.",
		"You're the Tony Stark to my Peter Parker.",
		"You're the Miles Morales to my Spiderverse.",
		"You're the roo to my doo-doo-doo-doo.",
		"You're the doodle to my boring conference call.",
		"You're the Dwight Shrute to my Dunder Mifflin.",
		"You're the Creed Bratton to my conference meeting.",
		"You're the ace to my deck of cards.",
		"You're the water to my poorly maintained house plant.",
		"You're the boop to my snoot.",
		"You're the mmm to my bop.",
		"You're the Boardwalk to my Monopoly.",
		"You're the red butt to my recess.",
		"You're the memories to my moonlight.",
		"You're the monotone outfit to my cult uniform.",
		"You're the nightmares to my murder podcast obsession.",
		"You're the Scooby to my Doo.",
		"You're the top to my muffin.",
		"You're the sophisticated burn to my sassy Alex Trebek.",
		"You're the right to my Tinder swipe.",
		"You're the sideburns to my John Travolta.",
		"You're the main character kill-off to my Game of Thrones.",
		"You're the chocolate to my period week.",
		"You're the laugh track to my Big Bang Theory.",
		"You're the bread recipe to my quarantine.",
		"You're the vaccine to my COVID-19.",
		"You're the acceptance to my radical self.",
		"You're the bees to my knees.",
		"You're the pajamas to my cat.",
		"You're the subtitles to my action movie.",
		"You're the joke to my awkward moment.",
		"You're the cheddar biscuits to my Red Lobster.",
		"You're the double tap to my IG post.",
		"You're the double knot to my running shoes.",
		"You're the free bread to my overpriced dinner.",
		"You're the XL chocolate bar to Halloween.",
		"You're the Usher to my early 2000's club night.",
		"You're the luxury candle to my living room.",
		"You're the free toothbrush to my dentist appointment.",
		"You're the 'all done' to my pap smear.",
		"You're the "

		
			
		);

function randomYoure() {
  var randomYoure = youre[Math.floor(Math.random() * youre.length)];
  document.getElementById('randomYoure').value = randomYoure;
}


function copy() {
  let randomYoure = document.getElementById("randomYoure");
  randomYoure.select();
  document.execCommand("copy");
}